services:
  go-chat:
    build: .
    container_name: go-chat
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["/entrypoint.sh", "air", "-c",".air.toml"]

networks:
  app-network:
    driver: bridge

