services:
  go-chat:
    build: .
    container_name: go-chat
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

